example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_nama = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_mywatchlist
from mywatchlist.views import show_xml
from mywatchlist.views import show_json

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_mywatchlist, name='show_mywatchlist'),
    path('html/', show_mywatchlist, name='show_mywatchlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import *
# from todolist.views import show_todolist
# from todolist.views import register
# from todolist.views import login_user
# from todolist.views import logout_user
# from todolist.views import create_task


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create_task/', create_task, name='create_task'),
    path('hapus_task/<int:task_id>', hapus_task, name='hapus_task'),
    path('update_task/<int:task_id>', update_task, name='update_task'),
    path('json/', show_todolist_json, name='show_todolist_json'),
    path('add/', add_task_json, name='add_task_json'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class WishlistFilmKu(models.Model):
    film_watched = models.BooleanField()
    film_title = models.TextField()
    film_rating = models.IntegerField()
    film_release_date = models.TextField()
    film_review = models.TextField()

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

class ItemTodolist(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.TextField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem
# TODO: Create your views here.

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Afiq Ilyasa Akmal'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from django.shortcuts import render
from mywatchlist.models import WishlistFilmKu

from django.http import HttpResponse
from django.core import serializers

# Create your views here.
def show_mywatchlist(request):
    data_barang_mywatchlist = WishlistFilmKu.objects.all()
    sudahDitonton = 0
    belumDitonton = 0
    pesan = ""
    for i in data_barang_mywatchlist:
        if i.film_watched == True:
            sudahDitonton += 1
        else:
            belumDitonton += 1
    if sudahDitonton >= belumDitonton:
        pesan = "Selamat, kamu sudah banyak menonton!"
    else:
        pesan = "Wah, kamu masih sedikit menonton!"
    context ={
        'list_film': data_barang_mywatchlist,
        'nama': 'Afiq Ilyasa Akmal',
        'pesan': pesan
    }
    return render(request, "mywatchlist.html", context)

def show_xml(request):
    data = WishlistFilmKu.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = WishlistFilmKu.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

todolist/views.py
import datetime
from django.shortcuts import render

# Registrasi
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

# Login
from django.contrib.auth import authenticate, login

# Logout
from django.contrib.auth import logout
# Create your views here.

# Login required
from django.contrib.auth.decorators import login_required

# Cookies
from django.http import HttpResponseRedirect, HttpResponse
from django.core import serializers
from django.urls import reverse

from todolist.models import ItemTodolist

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    user = request.user
    task = ItemTodolist.objects.filter(user=user)
    context = {
        'nama': user.username,
        'tasks': task
    }
    return render(request, "todolist.html", context)

# Register
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')

    context = {'form': form}
    return render(request, 'register.html', context)

# Login
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)  # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))  # membuat response
            currentDate = datetime.date.today()
            response.set_cookie('last_login',
                                str(currentDate.strftime("%Y-%m-%d")))  # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

# Logout
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response


def create_task(request):
    if (request.method == "POST"):
        title = request.POST["title"]
        currentDate = datetime.date.today()
        date = currentDate.strftime("%Y-%m-%d")
        description = request.POST["description"]
        task = ItemTodolist(user=request.user, title=title,date=date, description=description)
        task.save()
        return redirect('todolist:show_todolist')
    
    return render(request, 'create_task.html')

def hapus_task(request, task_id):
    deleted_item = ItemTodolist.objects.get(pk=task_id)
    deleted_item.delete()
    return redirect('todolist:show_todolist')

def update_task(request, task_id):
    updated_task = ItemTodolist.objects.get(pk=task_id)
    if updated_task.is_finished:
        updated_task.is_finished = False
    else:
        updated_task.is_finished = True
    updated_task.save()
    return redirect('todolist:show_todolist')

@login_required(login_url='/todolist/login/')
def show_todolist_json(request):
    tasks = ItemTodolist.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', tasks), content_type='application/json')

def add_task_json(request):
    if (request.method == "POST"):
        title = request.POST.get('title')
        description = request.POST.get('description')
        currentDate = datetime.date.today()
        date = currentDate.strftime("%Y-%m-%d")
        task = ItemTodolist.objects.create(user=request.user, date=date, title=title, description=description)
        task.save()
    return HttpResponse('')

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1>Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>Afiq Ilyasa Akmal</p>

  <h5>Student ID: </h5>
  <p>2106751291</p>

  <table>
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <th>{{barang.item_name}}</th>
          <th>{{barang.item_price}}</th>
          <th>{{barang.item_stock}}</th>
          <th>{{barang.rating}}</th>
          <th>{{barang.description}}</th>
          <th>{{barang.item_url}}</th>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
<style>
    @import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,800;1,400;1,800&display=swap');
    body {
        font-family: "Open Sans", sans-serif;
        font-weight: 500;
    }

    .bungkus {
        width: 720px;
        margin: 0 auto;
    }

    h1.title {
        text-align: center;
        color: brown;
    }

    p {
        font-weight: 400;
    }

    .identity {
        border-bottom: 1px #000 dotted;
    }

</style>
{% extends 'base.html' %}

 {% block content %}
<div class="bungkus">
  <h1 class="title">Assignment 3 - Platform-based Programming</h1>
    <div class="identity">
        <h5>Name: </h5>
        <p>Afiq Ilyasa Akmal</p>
        <h5>Student ID: </h5>
        <p>2106751291</p>
    </div>

     </br>


  <table>
    <tr>
      <th><p>Watched</p></th>
      <th><p>Title</p></th>
      <th><p>Rating</p></th>
      <th><p>Release date</p></th>
      <th><p>Review</p></th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for film in list_film %}
      <tr>
          <th><p>{{film.film_watched}}</p></th>
          <th><p>{{film.film_title}}</p></th>
          <th><p>{{film.film_rating}}</p></th>
          <th><p>{{film.film_release_date}}</p></th>
          <th><p>{{film.film_review}}</p></th>
      </tr>
    {% endfor %}
  </table>

     <h2>Pesan: </h2>
  <p>{{pesan}}</p>
</div>
 {% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
     <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href=" https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}

</body>

</html>

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}

<div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div class="d-inline-flex flex-column align-items-center rounded-4 bg-light p-5 mb-5 bg-white rounded">
    <h1>Create Task</h1>

    <form method="POST" action="" class="d-flex flex-column">
        {% csrf_token %}
        <div class="d-flex flex-column mb-2">
            <label for="create-task" class="form-label">Title</label>
            <input class="form-control" type="text" name="title" placeholder="Enter your title here..">
        </div>
        <div class="d-flex flex-column mb-2">
            <label for="create-task" class="form-label">Description</label>
            <textarea class="form-control" name="description" placeholder="Enter your description here.." rows=4></textarea>
        </div>
        <div class="d-flex flex-column mb-2">
            <input type="submit" value="Create task!">
        </div>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
  </div>
</div>
</div>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div class="d-inline-flex flex-column align-items-center rounded-4 bg-light p-5 mb-5 bg-white rounded">
    <h1>Login</h1>

    <form method="POST" action="" class="d-flex flex-column">
        {% csrf_token %}
        <div class="d-flex flex-column mb-2">
            <input type="text" name="username" placeholder="Username" class="form-control">
        </div>
         <div class="d-flex flex-column mb-2">
             <input type="password" name="password" placeholder="Password" class="form-control">
         </div>
         <div class="d-flex flex-column mb-2">
             <input class="btn btn-primary btn-block mb-4" type="submit" value="Login">
             <a href="{% url 'todolist:register' %}" class="btn btn-danger btn-xs" type="submit" value="Login">Register</a>
         </div>
    </form>

    {% if messages %}
            {% for message in messages %}
                <span class="text-danger">{{ message }}</span>
            {% endfor %}
    {% endif %}

  </div>
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}
<div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div class="d-flex flex-column align-items-center rounded-4 bg-light p-5 mb-5 bg-white rounded">
    <h1>Register</h1>

        <form method="POST"  class="d-flex flex-column">
            {% csrf_token %}
            <div class="d-flex flex-column mb-2">
                {{ form.as_table }}
            </div>
             <div class="d-flex flex-column mb-2">
                <input class="btn btn-primary btn-block mb-4" type="submit" value="Register">
             </div>
               <div class="d-flex flex-column mb-2">
                   <span class="text-primary"><p class = "text-center">Already registered? <a href="{% url 'todolist:login' %}" class="btn btn-danger btn-xs" type="submit" value="Login">Login here</a></p></span>
                </div>
        </form>
  </div>
</div>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<title>Todo List</title>
{% endblock meta %}

{% block content %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a href="#" class="navbar-brand">Hello, {{ nama }}</a>
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
                <a href="{% url 'todolist:create_task' %}" class="nav-item nav-link active">Create Task</a>
                <a href="{% url 'todolist:logout' %}" class="nav-item nav-link">Logout</a>
            </div>
            <div class="navbar-nav ms-auto">
<button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
  Create Task (modal)
</button>
            </div>
        </div>
    </div>
</nav>

    <div class="w-100 vh-100 d-flex justify-content-center align-items-center">
  <div class="d-flex flex-column align-items-center rounded-4 bg-light p-5 mb-5 bg-white rounded">


    <div class='row card-group kontainer'>
     {% comment %} Tambahkan data di bawah baris ini {% endcomment %}

    </div>
  </div>
    </div>

    <!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Create Task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" action="" class="d-flex flex-column">
        {% csrf_token %}
        <div class="d-flex flex-column mb-2">
            <label for="create-task" class="form-label">Title</label>
            <input class="form-control" type="text" id= "title-task" name="title" placeholder="Enter your title here..">
        </div>
        <div class="d-flex flex-column mb-2">
            <label for="create-task" class="form-label">Description</label>
            <textarea class="form-control" name="description"  id="desc-task" placeholder="Enter your description here.." rows=4></textarea>
        </div>
    </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="new-task-btn btn-primary" data-bs-dismiss="modal">Save</button>
      </div>
    </div>
  </div>
</div>
    <script>
    function getTask() {
      $.get('/todolist/json/', function(data){
      let data_todolist = '';
      for (let i=0; i<data.length; i++){
        let is_finished = data[i].fields.is_finished ? 'Done':'In progress';
        data_todolist += `
        <div class="col-4">
    <div class="card h-100 ">
      <div class="card-body">
        <h3 class="card-title">${data[i].fields.title}</h3>
            <p class="font-weight-bold blue-text">
                ${data[i].fields.description}
            </p>
        <h6 class="card-text">
            ${is_finished}
        </h6>
      </div>
      <div class="card-footer">
        <small class="text-muted">Added: ${data[i].fields.date}  </small><a href="/todolist/update_task/${data[i].pk}" class="btn btn-primary">Update Task</a>
      </div>
    </div>
  </div>
        `;
        $('.kontainer').html(data_todolist);
      }
    })
    }

    $(document).ready( function(){
      $.get("/todolist/json/", getTask);

      $('.new-task-btn').click( function(){
        let title = $('#title-task').val();
        let description = $('#desc-task').val();
        let CSRFtoken = $('input[name="csrfmiddlewaretoken"]').val();
        $.post('/todolist/add/', {
          title: title,
          description: description,
          csrfmiddlewaretoken: CSRFtoken
        }, $.get("/todolist/json/", getTask))

      })
    })
  </script>
{% endblock content %}